@startuml cancelling-workflow


actor "Operator" as operator
entity Workflow as workflow
participant "Tink Agent" as agent
participant "Tink Server" as server
control "Tink Controller" as controller

operator -> workflow : Delete
workflow -// server : Notified of change
server -> agent : Cancel Workflow
agent -> agent : Cancel
agent -// server : Publish Canceled
server -> workflow : Update Status(Canceled)
workflow -// controller : Notified of change
controller -> workflow : Remove finalizer

@enduml